# Generated by Django 5.2.4 on 2025-07-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='archivo',
        ),
    ]
