# Generated by Django 5.2.4 on 2025-07-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_remove_documento_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='nombre',
            new_name='nombre_del_archivo',
        ),
    ]
